---
title: "Sub-40 Murph Progression"
output: html_document
knit: (function(inputFile, encoding) { 
    rmarkdown::render(inputFile,
                      encoding=encoding, 
                      output_file=file.path('docs/index.html')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
pacman::p_load(dplyr,tidyr,lubridate,DT,data.table,ggplot2)
```

# Load CSV files


```{r }

csv_files = list.files(path = "data",full.names = T)
```

# Append Files

```{r}

df = 
  rbindlist(lapply(csv_files,function(x) {
  date = ymd(gsub("data/","",x))
  read.csv(x) %>% 
    as_tibble() %>% 
    dplyr::mutate(date=paste0(date)) %>% 
    dplyr::relocate(date)
})) %>% 
  dplyr::mutate(Time=gsub("\\..$","",Time)) %>% 
  dplyr::mutate(Cumulative.Time=gsub("\\..$","",Cumulative.Time)) %>% 
  dplyr::mutate(Time=paste0("0:",Time))

```

# Lap dictionary

```{r}

start = "Start"

runs = rep("400m run",4)

cindys = t(outer(paste0("Double-Cindy #",seq(1,10)),c(" - 10 Pull-Ups"," - 20 Push-ups"," - 30 Squats"), FUN = "paste0"))
dim(cindys) <- NULL

exercise_types = c("Start",rep("Run",4),rep(c("Pull-Ups","Push-ups","Squats"),10),rep("Run",4))

lap_dictionary = data.frame(Description = factor(c(start,runs,cindys,runs))) %>% 
  dplyr::mutate(Laps = paste0(seq(nrow(.))-1)) %>% 
  dplyr::mutate(Exercise=factor(exercise_types))

```

# Explore Datatable

```{r}

df.joined = lap_dictionary %>% 
  left_join(df) %>% 
  dplyr::mutate(date=ymd(ifelse(is.na(date),lead(date),date))) %>% 
  dplyr::mutate(Laps=as.integer(Laps)) %>% 
  dplyr::mutate(Time=ifelse(is.na(Time),"0:00.0",Time)) %>%  
  dplyr::mutate(Time=hms(Time)) %>% 
  dplyr::mutate(Cumulative.Time=ifelse(is.na(Cumulative.Time),"0:00.0",Cumulative.Time)) %>% 
  dplyr::mutate(Cumulative.Time=lubridate::ymd_hms(paste0(Sys.Date()," 00:",Cumulative.Time))) %>% 
  dplyr::mutate(Distance=ifelse(is.na(Distance),0,Distance)) %>% 
  dplyr::mutate(Avg.Pace=ifelse(is.na(Avg.Pace),"0",Avg.Pace)) %>% 
  dplyr::mutate(Avg.HR=ifelse(is.na(Avg.HR),NA,Avg.HR)) %>% 
  dplyr::mutate(Max.HR=ifelse(is.na(Max.HR),NA,Max.HR)) %>% 
  dplyr::mutate(Elev.Gain=ifelse(is.na(Elev.Gain),NA,Elev.Gain)) %>% 
  dplyr::mutate(Elev.Loss=ifelse(is.na(Elev.Loss),NA,Elev.Loss)) %>% 
  dplyr::mutate(Avg.Run.Cadence=ifelse(is.na(Avg.Run.Cadence),NA,Avg.Run.Cadence)) %>% 
  dplyr::mutate(Avg.Stride.Length=ifelse(is.na(Avg.Stride.Length),0,Avg.Stride.Length)) %>% 
  dplyr::mutate(Calories=ifelse(is.na(Calories),0,Calories)) %>% 
  dplyr::mutate(Avg.Temperature=ifelse(is.na(Avg.Temperature),30,Avg.Temperature))

df.joined %>% 
  DT::datatable()

```


# Visualizing one Murph

```{r}

df.joined %>% 
  ggplot(.,aes(x=Cumulative.Time,y=Laps)) +
  geom_line() +
  geom_point(aes(color=Exercise,size=Max.HR)) +
  scale_x_datetime(breaks = scales::breaks_width("2 min"),date_labels = "%Mm") +
  theme_bw() +
  coord_flip() + 
  theme(axis.text.x = element_blank(),
        legend.position = "bottom") +
  labs(y=NULL,x=NULL,title="Murph")

```

# Benchmarking individual

```{r}

df.joined %>% 
  group_by(date,Exercise) %>% 
  dplyr::mutate(Rang=rank(Cumulative.Time)) %>% 
  dplyr::mutate(Time=as.numeric(Time)) %>% 
  filter(!Exercise=="Start") %>% 
  ggplot(.,aes(x=Rang,y=Time)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Exercise,scales="free") +
  theme_bw() + 
  labs(y="seconds",x="Round",title="Murph") +
  scale_x_continuous(breaks=seq(1,10))

```

# Proportion

```{r}

df.joined %>% 
  filter(!Exercise=="Start") %>% 
  dplyr::mutate(Time=as.numeric(Time)) %>% 
  group_by(date,Exercise) %>% 
  summarise(Time=sum(Time)/60) %>% 
  group_by(date) %>% 
  dplyr::mutate(Time_frac=Time/sum(Time)) %>% 
  dplyr::mutate(Label=paste0(Exercise," (",seconds_to_period(Time*60)," - ",scales::percent(Time_frac),")")) %>% 
  ungroup() %>% 
  ggplot(.,aes(x=date,y=Time,label=Label,fill=Time)) +
  geom_bar(stat = "identity") +
  geom_text(size = 5, position = position_stack(vjust = 0.5),color="white") +
  theme_bw() +
  theme(legend.position="null") 
  

```

# Detailed

```{r fig.height=12,fig.width=4}

df.joined %>% 
  filter(!Exercise=="Start") %>% 
  dplyr::mutate(Time=as.numeric(Time)) %>% 
  group_by(date,Exercise,Laps) %>% 
  summarise(Time=sum(Time)/60) %>% 
  group_by(date,Exercise) %>% 
  dplyr::mutate(Time_frac=Time/sum(Time)) %>% 
  dplyr::mutate(Label=paste0(Laps," - ",Exercise," (",seconds_to_period(Time*60)," - ",scales::percent(Time_frac),")")) %>% 
  ungroup() %>% 
  ggplot(.,aes(x=date,y=Time,label=Label,fill=Time)) +
  geom_bar(stat = "identity") +
  geom_text(size = 2, position = position_stack(vjust = 0.5),color="white") +
  theme_bw() +
  theme(legend.position="null") 
  

```

# Heart rate

```{r}

df.joined %>% 
  filter(!Exercise=="Start") %>% 
  dplyr::select(Laps,Exercise,Avg.HR,Max.HR) %>% 
  gather(stat,value,Avg.HR,Max.HR) %>% 
  ggplot(.,aes(x=Laps,y=value,color=stat)) +
  geom_line() +
  geom_point(aes(color=Exercise)) +
  scale_y_continuous(breaks=seq(0,175,by=5),limits=c(NA,175)) +
  scale_x_continuous(breaks=seq(0,50)) +
  theme_bw() + 
  theme(axis.text.x = element_blank(),
        legend.position = "bottom") +
  labs(y="Heart Rate") +
  geom_text(aes(label=value),vjust=-0.5,size=3)

```
